import nicole from "../../../../../imgs/avatar_4.JPG";
import jacob from "../../../../../imgs/jacob.jpg";
import john from "../../../../../imgs/avatar_6.JPG";
 const staticNotifications = [ {
    id: 1,
    priority: "High",
    priorityNumber: 3,
    message: "It's Nicole Miller's birthday tomorrow. Don't forget to send her a gift!",
    fullName: "Nicole",
    link: "/de",
    className: "Birthday",
    read: false,
    viewed: false,
    dismissed: false,
    startDay: "2021-08-24",
    date: "1996-09-08",
    image: nicole,
  },
  {
    id: 2,
    priority: "Medium",
    priorityNumber: 2,
    message:
      "Tomorrow is the international pizza day. View your options for spoiling your team!",
    className: "bg-pink",
    link: "/task-board",
    startDay: "2021-08-24",
    date: "1996-09-08",
    read: false,
    dismissed: false,
    viewed: false,
  },
  {
    id: 3,
    priority: "High",
    priorityNumber: 3,
    fullName: "Fourth of July",
    message:
      "The Fourth of July celebration is in one month. Ensure there are food options for those with allergies and dietary preferences.",
      startDay: "2021-08-24",
      date: "2024-12-08",
    className: "bg-info",
    read: false,
    dismissed: false,
    viewed: false,
  },
  {
    id: 4,
    priority: "High",
    priorityNumber: 3,
    message: "Note! A meeting was arranged with Nicole when she is at home",
    link: "/departments",
    startDay: "2021-08-24",
    date: "1996-09-08",
    read: false,
    viewed: false,
    dismissed: false,
    image: nicole,
  },
  {
    id: 5,
    priority: "Medium",
    priorityNumber: 2,
    message:
      "Jacob used over 20 days of sick days in the last quarter. Let him know he has reached his limit.",
      startDay: "2021-08-24",
      date: "1996-09-08",
    read: false,
    viewed: false,
    dismissed: false,
    image: jacob,
  },
  {
    id: 6,
    priority: "Medium",
    priorityNumber: 2,
    message: "John's work routine has significantly changed.",
    link: "/departments",
    startDay: "2021-08-24",
    date: "1996-09-08",
    read: false,
    dismissed: false,
    viewed: false,
    image: john,
  },
  {
    id: 7,
    priority: "Low",
    priorityNumber: 1,
    message:
      "A Maccabi Tel-Aviv Soccer Game is coming up in a week. Wanna find out who from your workers is a fan of the team?",
    link: "/task-board",
    startDay: "2021-08-24",
    date: "1996-09-08",
    read: false,
    viewed: false,
    dismissed: false,
  },
  {
    id: 8,
    priority: "High",
    priorityNumber: 3,
    message:
      "John is flying to rome tomorrow - lets make it a real vacation for him.",
    link: "/low-priority-notification",
    startDay: "2021-08-24",
    date: "1996-09-08",
    className: "vacation",
    read: false,  
    dismissed: false,
    viewed: false,
    image: john,
  },
]

export default staticNotifications;