services:
  server:
    build:
      context: .
    environment:
      - NODE_ENV:production
      - MONGO_URI
    ports:
      - 5000:5000
    develop:
      watch:
        - action: sync
          path: .
          target: /backend
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
